# http://docs.travis-ci.com/user/languages/r/
language: r

cache: packages

r:
  - release

after_success:
  - Rscript -e 'library(covr);coveralls()'

warnings_are_errors: false

notifications:
  email:
    - t.zajac@uw.edu.pl
    
r_github_packages:
  - ZajacT/ASIA1