# http://docs.travis-ci.com/user/languages/r/
language: r
cache: packages

r:
  - release

after_success:
  - Rscript -e 'library(covr);coveralls()'

warnings_are_errors: false

notifications:
  email:
    recipients:
      - t.zajac@uw.edu.pl
      - tomek@zozlak.org
    on_success: change # default: change
    on_failure: always # default: always

r_github_packages:
  - ZajacT/ASIA1
